delete-merged-branches = true
status = ["check-ci-config", "e2e-build", "e2e-run", "rustfmt", "rust-unit-tests", "rust-unused-deps", "rust-cargo-deny", "rust-lint", "cpp-lint", "publish"]
timeout-sec = 900
