[package]
name = "pps-api"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
uuid = { version = "0.8.2", features = ["serde"] }
